export const LOGIN = 'AUTH/LOGIN'
export const REGISTRATION = 'AUTH/REGISTRATION'
export const LOGOUT = 'AUTH/LOGOUT'
export const AUTH = 'AUTH/AUTH'
export const SUCCESS_LOGIN = 'AUTH/SUCCESS_LOGIN'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ERROR = 'APP/SHOW_ERROR'
export const HIDE_ERROR = 'APP/HIDE_ERROR'

export const TASK_SEARCH = 'APP/TASK_SEARCH'


export const SHOW_LOADER_USER_UPDATE = 'APP/SHOW_LOADER_USER_UPDATE'
export const HIDE_LOADER_USER_UPDATE = 'APP/HIDE_LOADER_USER_UPDATE'
export const SHOW_LOADER_USER_PASSWORD_UPDATE = 'APP/SHOW_LOADER_USER_PASSWORD_UPDATE'
export const HIDE_LOADER_USER_PASSWORD_UPDATE = 'APP/HIDE_LOADER_USER_PASSWORD_UPDATE'
export const SHOW_LOADER_TASKS_LOADING = 'APP/SHOW_LOADER_TASKS_LOADING'
export const HIDE_LOADER_TASKS_LOADING = 'APP/HIDE_LOADER_TASKS_LOADING'
export const SHOW_LOADER_USERS_LOADING = 'APP/SHOW_LOADER_USERS_LOADING'
export const HIDE_LOADER_USERS_LOADING = 'APP/HIDE_LOADER_USERS_LOADING'

export const CREATE_TASK = 'TASK/CREATE'
export const GET_TASK = 'TASK/GET_TASK'
export const GET_TASK_STATE = 'TASK/GET_TASK_STATE'
export const DELETE_TASK = 'TASK/DELETE_TASK'
export const SUCCESS_CREATE_TASK = 'TASK/SUCCESS_CREATE_TASK'
export const UPDATE_TASK = 'TASK/UPDATE_TASK'
export const SUCCESS_UPDATE_TASK = 'TASK/UPDATE_SUCCESS_TASK'

export const TASK_SHOW_LOADING = 'TASK/TASK_SHOW_LOADING'
export const TASK_HIDE_LOADING = 'TASK/TASK_HIDE_LOADING'


export const GET_USER = 'USER/GET_USER'
export const SUCCESS_GET_USER = 'USER/SUCCESS_GET_USER'
export const UPDATE_USER = 'USER/UPDATE_USER'
export const SUCCESS_UPDATE_USER = 'USER/SUCCESS_UPDATE_USER'
export const UPDATE_USER_PASSWORD = 'USER/UPDATE_PASSWORD_USER'
export const SUCCESS_UPDATE_USER_PASSWORD= 'USER/SUCCESS_UPDATE_USER_PASSWORD'

export const SUCCESS_UPDATE_TASKS = 'SUCCESS_UPDATE_TASKS'


export const GET_USERS = 'USERS/GET_USERS'
export const SUCCESS_GET_USERS = 'USERS/SUCCESS_GET_USERS'